baseURL = "http://dfsnow.me"
title = "Dan Snow"
copyright = ""

theme = "hugo-theme-minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "Data Diver and Vim Enthusiast"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "Daniel Snow"
  copyrightStartYear = "2018"
  favicon = "favicon.ico"
  hideEntryNavigation = true
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "|"

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  github = "dfsnow"
  email = "dfsnow@uchicago.edu"
  linkedin = "dfsnow"

[author]
  name = "Dan Snow"

[author.social]
  github = "dfsnow"
  email = "dfsnow@uchicago.edu"
  linkedin = "dfsnow"

[permalinks]
  page = "/:slug/"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
