baseURL = "https://dfsnow.me"
title = "Dan Snow"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = false

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "hot_take: snake_case_is_best_case"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Daniel Snow"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = true # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = true

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "|"

[params.social]
email = "dfsnow@uchicago.edu"
twitter = "snowdfs"
github = "dfsnow"
linkedin = "dfsnow"

[params.social.config]
platforms = ["email","github","facebook","twitter","instagram","codepen","linkedin","telegram"]

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Jupyter"
identifier = "jupyterhub"
url = "https://lab.dfsnow.me:8000"

[[menu.main]]
name = "RStudio"
identifier = "rstudio"
url = "https://lab.dfsnow.me"

[[menu.main]]
name = "Data"
identifier = "data"
url = "https://lab.dfsnow.me:8080"

[[menu.main]]
name = "Grafana"
identifier = "grafana"
url = "https://lab.dfsnow.me:3000"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
